export const mealsData = [{
  idMeal: '52977',
  strMeal: 'Corba',
  strDrinkAlternate: null,
  strCategory: 'Side',
  strArea: 'Turkish',
  strInstructions:
        `Pick through your lentils for any foreign debris, rinse them 2 or 3 times, 
      drain, and set aside.  Fair warning, this will probably turn your lentils 
      into a solid block that you’ll have to break up later\r\nIn a large pot over
       medium-high heat, sauté the olive oil and the onion with a pinch of salt 
       for about 3 minutes, then add the carrots and cook for another 3 minutes.
       \r\nAdd the tomato paste and stir it around for around 1 minute. Now add 
       the cumin, paprika, mint, thyme, black pepper, and red pepper as quickly as
        you can and stir for 10 seconds to bloom the spices. Congratulate yourself
         on how amazing your house now smells.\r\nImmediately add the lentils, 
         water, broth, and salt. Bring the soup to a (gentle) boil.\r\nAfter it 
         has come to a boil, reduce heat to medium-low, cover the pot halfway, and
          cook for 15-20 minutes or until the lentils have fallen apart and the 
          carrots are completely cooked.\r\nAfter the soup has cooked and the 
          lentils are tender, blend the soup either in a blender or simply use a 
          hand blender to reach the consistency you desire. Taste for seasoning 
          and add more salt if necessary.\r\nServe with crushed-up crackers, torn 
          up bread, or something else to add some extra thickness.  You could also
           use a traditional thickener (like cornstarch or flour), but I prefer to
            add crackers for some texture and saltiness.  Makes great leftovers, 
            stays good in the fridge for about a week.`,
  strMealThumb: 'https://www.themealdb.com/images/media/meals/58oia61564916529.jpg',
  strTags: 'Soup',
  strYoutube: 'https://www.youtube.com/watch?v=VVnZd8A84z4',
  strIngredient1: 'Lentils',
  strIngredient2: 'Onion',
  strIngredient3: 'Carrots',
  strIngredient4: 'Tomato Puree',
  strIngredient5: 'Cumin',
  strIngredient6: 'Paprika',
  strIngredient7: 'Mint',
  strIngredient8: 'Thyme',
  strIngredient9: 'Black Pepper',
  strIngredient10: 'Red Pepper Flakes',
  strIngredient11: 'Vegetable Stock',
  strIngredient12: 'Water',
  strIngredient13: 'Sea Salt',
  strIngredient14: '',
  strIngredient15: '',
  strIngredient16: '',
  strIngredient17: '',
  strIngredient18: '',
  strIngredient19: '',
  strIngredient20: '',
  strMeasure1: '1 cup ',
  strMeasure2: '1 large',
  strMeasure3: '1 large',
  strMeasure4: '1 tbs',
  strMeasure5: '2 tsp',
  strMeasure6: '1 tsp ',
  strMeasure7: '1/2 tsp',
  strMeasure8: '1/2 tsp',
  strMeasure9: '1/4 tsp',
  strMeasure10: '1/4 tsp',
  strMeasure11: '4 cups ',
  strMeasure12: '1 cup ',
  strMeasure13: 'Pinch',
  strMeasure14: ' ',
  strMeasure15: ' ',
  strMeasure16: ' ',
  strMeasure17: ' ',
  strMeasure18: ' ',
  strMeasure19: ' ',
  strMeasure20: ' ',
  strSource: 'https://findingtimeforcooking.com/main-dishes/red-lentil-soup-corba/',
  strImageSource: null,
  strCreativeCommonsConfirmed: null,
  dateModified: null,
}];

export const drinksData = [{
  idDrink: '11118',
  strDrink: 'Blue Margarita',
  strDrinkAlternate: null,
  strTags: null,
  strVideo: null,
  strCategory: 'Ordinary Drink',
  strIBA: null,
  strAlcoholic: 'Alcoholic',
  strGlass: 'Cocktail glass',
  strInstructions: `Rub rim of cocktail glass with lime juice. 
    Dip rim in coarse salt. 
    Shake tequila, blue curacao, and lime juice with ice, 
    strain into the salt-rimmed glass, and serve.`,
  strInstructionsES: null,
  strInstructionsDE: `Den Rand des Cocktailglases mit Limettensaft einreiben.
     Den Rand in grobes Salz tauchen. 
     Tequila, blauen Curacao und Limettensaft mit Eis schütteln
     , in das mit Salz umhüllte Glas abseihen und servieren.`,
  strInstructionsFR: null,
  strInstructionsIT: `Strofinare il bordo del bicchiere da cocktail con succo di lime.
     Immergere il bordo nel sale grosso.
     Shakerare tequila, blue curacao e succo di lime con ghiaccio,
     filtrare nel bicchiere bordato di sale e servire.`,
  'strInstructionsZH-HANS': null,
  'strInstructionsZH-HANT': null,
  strDrinkThumb: 'https://www.thecocktaildb.com/images/media/drink/bry4qh1582751040.jpg',
  strIngredient1: 'Tequila',
  strIngredient2: 'Blue Curacao',
  strIngredient3: 'Lime juice',
  strIngredient4: 'Salt',
  strIngredient5: null,
  strIngredient6: null,
  strIngredient7: null,
  strIngredient8: null,
  strIngredient9: null,
  strIngredient10: null,
  strIngredient11: null,
  strIngredient12: null,
  strIngredient13: null,
  strIngredient14: null,
  strIngredient15: null,
  strMeasure1: '1 1/2 oz ',
  strMeasure2: '1 oz ',
  strMeasure3: '1 oz ',
  strMeasure4: 'Coarse ',
  strMeasure5: null,
  strMeasure6: null,
  strMeasure7: null,
  strMeasure8: null,
  strMeasure9: null,
  strMeasure10: null,
  strMeasure11: null,
  strMeasure12: null,
  strMeasure13: null,
  strMeasure14: null,
  strMeasure15: null,
  strImageSource: null,
  strImageAttribution: null,
  strCreativeCommonsConfirmed: 'Yes',
  dateModified: '2015-08-18 14:51:53',
}];

export const mealsData1 = {
  meals: [{
    idMeal: '52775',
    strMeal: 'Vegan Lasagna',
    strCategory: 'Vegan',
    strArea: 'Italian',
    strInstructions: '1) Preheat oven to 180 degrees celcius.',
    strMealThumb: 'https://www.themealdb.com/images/media/meals/rvxxuy1468312893.jpg',
    strTags: 'Vegan,Pasta',
    strIngredient1: 'green red lentils',
    strIngredient2: 'carrot',
    strIngredient3: 'onion',
    strIngredient4: 'zucchini',
    strIngredient5: 'coriander',
    strIngredient6: 'spinach',
    strIngredient7: 'lasagne sheets',
    strIngredient8: 'vegan butter',
    strIngredient9: 'flour',
    strIngredient10: 'soya milk',
    strIngredient11: 'mustard',
    strIngredient12: 'vinegar',
    strIngredient13: '',
    strIngredient14: '',
    strIngredient15: '',
    strMeasure1: '1 cups',
    strMeasure2: '1',
    strMeasure3: '1',
    strMeasure4: '1 small',
    strMeasure5: 'sprinking',
    strMeasure6: '150g',
    strMeasure7: '10',
    strMeasure8: '35g',
    strMeasure9: '4 tablespoons',
    strMeasure10: '300ml',
    strMeasure11: '1.5 teaspoons',
    strMeasure12: '1 teaspoon',
    strMeasure13: '',
    strMeasure14: '',
    strMeasure15: '',
    dateModified: null,
  }],
};

export const drinksData1 = {
  drinks: [{
    idDrink: '178365',
    strDrink: 'Gin Tonic',
    strDrinkAlternate: null,
    strTags: null,
    strVideo: null,
    strCategory: 'Cocktail',
    strIBA: null,
    strAlcoholic: 'Alcoholic',
    strGlass: 'Highball glass',
    strInstructions: 'Fill a highball glass with ice, pour the gin, top with tonic.',
    strInstructionsES: null,
    strInstructionsFR: null,
    'strInstructionsZH-HANS': null,
    'strInstructionsZH-HANT': null,
    strDrinkThumb: 'https://www.thecocktaildb.com/images/media/drink/qcgz0t1643821443.jpg',
    strIngredient1: 'Gin',
    strIngredient2: 'Tonic Water',
    strIngredient3: 'Lemon Peel',
    strIngredient4: 'Ice',
    strIngredient5: null,
    strIngredient6: null,
    strIngredient7: null,
    strIngredient8: null,
    strIngredient9: null,
    strIngredient10: null,
    strIngredient11: null,
    strIngredient12: null,
    strIngredient13: null,
    strIngredient14: null,
    strIngredient15: null,
    strMeasure1: '4 cl',
    strMeasure2: '10 cl',
    strMeasure3: '1 Slice',
    strMeasure4: 'cubes',
    strMeasure5: '',
    strMeasure6: '',
    strMeasure7: '',
    strMeasure8: null,
    strMeasure9: null,
    strMeasure10: null,
    strMeasure11: null,
    strMeasure12: null,
    strMeasure13: null,
    strMeasure14: null,
    strMeasure15: null,
    strImageSource: 'https://www.brunovanzan.com/wp-content/uploads/2020/01/gin-tonic.png',
    strImageAttribution: null,
    strCreativeCommonsConfirmed: 'No',
    dateModified: null,
  }],
};
