// henrique

const cocktailGlass = 'Cocktail glass';
const grandMarnier = 'Grand Marnier';
const ordinaryDrink = 'Ordinary Drink';
const collinsGlass = 'Collins Glass';
const shotGlass = 'Shot glass';
const baileysIrishCream = 'Baileys irish cream';

export const mockCarousel = {
  drinks: [{
    idDrink: '17222',
    strDrink: 'A1',
    strDrinkAlternate: null,
    strTags: null,
    strVideo: null,
    strCategory: 'Cocktail',
    strIBA: null,
    strAlcoholic: 'Alcoholic',
    strGlass: cocktailGlass,
    strInstructions: 'Pour all ingredients into a cocktail shaker,',
    strInstructionsES: 'Vierta todos los ingredientes en una coctelera,',
    strInstructionsDE: 'Alle Zutaten in einen Cocktailshaker geben,',
    strInstructionsFR: null,
    strInstructionsIT: 'Versare tutti gli ingredienti in uno shaker,',
    'strInstructionsZH-HANS': null,
    'strInstructionsZH-HANT': null,
    strDrinkThumb: 'https://www.thecocktaildb.com/images/media/drink/2x8thr1504816928.jpg',
    strIngredient1: 'Gin',
    strIngredient2: grandMarnier,
    strIngredient3: 'Lemon Juice',
    strIngredient4: 'Grenadine',
    strIngredient5: null,
    strIngredient6: null,
    strIngredient7: null,
    strIngredient8: null,
    strIngredient9: null,
    strIngredient10: null,
    strIngredient11: null,
    strIngredient12: null,
    strIngredient13: null,
    strIngredient14: null,
    strIngredient15: null,
    strMeasure1: '1 3/4 shot ',
    strMeasure2: '1 Shot ',
    strMeasure3: '1/4 Shot',
    strMeasure4: '1/8 Shot',
    strMeasure5: null,
    strMeasure6: null,
    strMeasure7: null,
    strMeasure8: null,
    strMeasure9: null,
    strMeasure10: null,
    strMeasure11: null,
    strMeasure12: null,
    strMeasure13: null,
    strMeasure14: null,
    strMeasure15: null,
    strImageSource: null,
    strImageAttribution: null,
    strCreativeCommonsConfirmed: 'No',
    dateModified: '2017-09-07 21:42:09',
  },
  {
    idDrink: '15997',
    strDrink: 'GG',
    strDrinkAlternate: null,
    strTags: null,
    strVideo: null,
    strCategory: ordinaryDrink,
    strIBA: null,
    strAlcoholic: 'Optional alcohol',
    strGlass: collinsGlass,
    strInstructions: 'Pour the Galliano liqueur over ice.',
    strInstructionsES: null,
    strInstructionsDE: 'Den Galliano-Likör über Eis gießen.',
    strInstructionsFR: null,
    strInstructionsIT: 'Versare il liquore Galliano su ghiaccio.',
    'strInstructionsZH-HANS': null,
    'strInstructionsZH-HANT': null,
    strDrinkThumb: 'https://www.thecocktaildb.com/images/media/drink/vyxwut1468875960.jpg',
    strIngredient1: 'Galliano',
    strIngredient2: 'Ginger ale',
    strIngredient3: 'Ice',
    strIngredient4: null,
    strIngredient5: null,
    strIngredient6: null,
    strIngredient7: null,
    strIngredient8: null,
    strIngredient9: null,
    strIngredient10: null,
    strIngredient11: null,
    strIngredient12: null,
    strIngredient13: null,
    strIngredient14: null,
    strIngredient15: null,
    strMeasure1: '2 1/2 shots ',
    strMeasure2: null,
    strMeasure3: null,
    strMeasure4: null,
    strMeasure5: null,
    strMeasure6: null,
    strMeasure7: null,
    strMeasure8: null,
    strMeasure9: null,
    strMeasure10: null,
    strMeasure11: null,
    strMeasure12: null,
    strMeasure13: null,
    strMeasure14: null,
    strMeasure15: null,
    strImageSource: null,
    strImageAttribution: null,
    strCreativeCommonsConfirmed: 'No',
    dateModified: '2016-07-18 22:06:00',
  },
  {
    idDrink: '13501',
    strDrink: 'ABC',
    strDrinkAlternate: null,
    strTags: null,
    strVideo: null,
    strCategory: 'Shot',
    strIBA: null,
    strAlcoholic: 'Alcoholic',
    strGlass: shotGlass,
    strInstructions: 'Layered in a shot glass.',
    strInstructionsES: 'Coloque todos los ingredientes en un vaso de chupito.',
    strInstructionsDE: 'Schichtaufbau in einem Schnapsglas.',
    strInstructionsFR: null,
    strInstructionsIT: 'Versa in ordine di lettera i vari ingredienti.',
    'strInstructionsZH-HANS': null,
    'strInstructionsZH-HANT': null,
    strDrinkThumb: 'https://www.thecocktaildb.com/images/media/drink/tqpvqp1472668328.jpg',
    strIngredient1: 'Amaretto',
    strIngredient2: baileysIrishCream,
    strIngredient3: 'Cognac',
    strIngredient4: null,
    strIngredient5: null,
    strIngredient6: null,
    strIngredient7: null,
    strIngredient8: null,
    strIngredient9: null,
    strIngredient10: null,
    strIngredient11: null,
    strIngredient12: null,
    strIngredient13: null,
    strIngredient14: null,
    strIngredient15: null,
    strMeasure1: '1/3 ',
    strMeasure2: '1/3 ',
    strMeasure3: '1/3 ',
    strMeasure4: null,
    strMeasure5: null,
    strMeasure6: null,
    strMeasure7: null,
    strMeasure8: null,
    strMeasure9: null,
    strMeasure10: null,
    strMeasure11: null,
    strMeasure12: null,
    strMeasure13: null,
    strMeasure14: null,
    strMeasure15: null,
    strImageSource: null,
    strImageAttribution: null,
    strCreativeCommonsConfirmed: 'No',
    dateModified: '2016-08-31 19:32:08',
  },
  {
    idDrink: '17225',
    strDrink: 'Ace',
    strDrinkAlternate: null,
    strTags: null,
    strVideo: null,
    strCategory: 'Cocktail',
    strIBA: null,
    strAlcoholic: 'Alcoholic',
    strGlass: 'Martini Glass',
    strInstructions: 'Shake all the ingredients in a cocktail shaker and',
    strInstructionsES: 'Agite todos los ingredientes en una coctelera con hielo y',
    strInstructionsDE: 'Alle Zutaten in einem Cocktailshaker mit Eis schütteln und',
    strInstructionsFR: null,
    strInstructionsIT: 'Shakerare tutti gli ingredienti in uno shaker e ghiaccio,',
    'strInstructionsZH-HANS': null,
    'strInstructionsZH-HANT': null,
    strDrinkThumb: 'https://www.thecocktaildb.com/images/media/drink/l3cd7f1504818306.jpg',
    strIngredient1: 'Gin',
    strIngredient2: 'Grenadine',
    strIngredient3: 'Heavy cream',
    strIngredient4: 'Milk',
    strIngredient5: 'Egg White',
    strIngredient6: null,
    strIngredient7: null,
    strIngredient8: null,
    strIngredient9: null,
    strIngredient10: null,
    strIngredient11: null,
    strIngredient12: null,
    strIngredient13: null,
    strIngredient14: null,
    strIngredient15: null,
    strMeasure1: '2 shots ',
    strMeasure2: '1/2 shot ',
    strMeasure3: '1/2 shot ',
    strMeasure4: '1/2 shot',
    strMeasure5: '1/2 Fresh',
    strMeasure6: null,
    strMeasure7: null,
    strMeasure8: null,
    strMeasure9: null,
    strMeasure10: null,
    strMeasure11: null,
    strMeasure12: null,
    strMeasure13: null,
    strMeasure14: null,
    strMeasure15: null,
    strImageSource: null,
    strImageAttribution: null,
    strCreativeCommonsConfirmed: 'No',
    dateModified: '2017-09-07 22:05:06',
  }],
};
